"""empty message

Revision ID: 9c0d59a8c006
Revises: c89d2455420f
Create Date: 2018-06-25 14:10:37.728201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0d59a8c006'
down_revision = 'c89d2455420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('portada', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'portada')
    # ### end Alembic commands ###
